### ISSUE TITLE
Keeping location info

### ISSUE THREAD

**Issue by zoggy** [mjambon/yojson#22]
Hello,

Is there any plan to keep some location information ? For example, we could have a `Loc` module, with an interface quite similar to the interface of the `Safe` module, but with constructors of the `json` type having a location information. This could be used to provide more useful error messages in applications.

Do you think it can easily be added to Yojson ? And would you be interested in a patch ?

**Comment by mjambon** [comment]
Yojson originally was designed to serve as the runtime library for atdgen. The lexer uses ocamllex with a [module-shadowing trick](https://github.com/mjambon/yojson/blob/master/read.mll#L2-L23) to avoid allocating a new position record for each token, saving something like 30% time.

Now I see that a bunch of people use yojson without atdgen. I don't understand fully why, but certainly don't mind.

There's no need to keep locations around with atdgen. Since the OCaml data structures are constructed at the same time as parsing, and once we have the OCaml data, there's no more error to expect. In that respect the yojson tree is different so I see why having locations would be useful.

With a bit more preprocessor hackery, we could create a new module in addition to `Safe`, `Basic`, and `Raw`. I must say I don't like that there are multiple modules to pick from. We could probably generate equivalents of these with locations, but now we get not 3 but 6 modules to pick from. I can't really tell whether it's just fine or if it will create a lot of confusion among users. And we don't want to break existing applications. Do you have an opinion?

**Comment by zoggy** [comment]
6 modules is a lot in my opinion. Personnally, I always use `Safe`. But looking at the code, keeping locations will result in large code duplication in the lexer, since the type of the tree would not be compatible with the existing one. I think I'll write my own small lib, then :)

**Comment by mjambon** [comment]
Go for it. It's difficult to have one library that's optimized for all purposes and the json format is so simple that it makes sense.
