### ISSUE TITLE
Failure "oops" from Yojson.Safe.to_channel

### ISSUE THREAD

**Issue by NathanReb** [mjambon/yojson#61]
I recently hit the `Failure "oops"` raised at https://github.com/mjambon/yojson/blob/master/lib/write.ml#L31.

I unfortunately haven't been able to reproduce it in a minimal example so far but here are the debug log and the `yojson` part of the stacktrace:

```
src="CKA_ALWAYS_SENSITIVE" start=0 len=20
```
```
Called from file "write.ml", line 52, characters 2-24
Called from file "write.ml", line 329, characters 4-21
Called from file "write.ml", line 284, characters 6-15
Called from file "write.ml", line 334, characters 2-24
Called from file "write.ml", line 290, characters 6-15
Called from file "write.ml", line 339, characters 2-29
Called from file "write.ml", line 284, characters 6-15
Called from file "write.ml", line 339, characters 2-29
Called from file "write.ml", line 290, characters 6-15
Called from file "write.ml", line 334, characters 2-24
Called from file "write.ml", line 290, characters 6-15
Called from file "write.ml", line 334, characters 2-24
Called from file "write.ml", line 290, characters 6-15
Called from file "write.ml", line 339, characters 2-29
Called from file "write.ml", line 290, characters 6-15
Called from file "write.ml", line 334, characters 2-24
Called from file "write.ml", line 457, characters 2-21
```

The error seems unrelated to the `Yojson.Safe.json` value which I can write to a file or string without any problem or even to a seemingly identical `out_channel` in utop.

The commit that triggers this exception doesn't change either the `open_out_gen` or the `Yojson.Safe.to_channel` calls so it's a bit of a nightmare to debug.

How about making this error more explicit, for example by reraising the caught exception instead of the `failwith` ?

**Comment by NathanReb** [comment]
Just to clarify: I don't think it's a bug from `yojson` but it could use a better error reporting, happy to contribute with a PR for the reraise if you feel like that's the right way to go!

**Comment by mjambon** [comment]
Oh, that's awful. Sorry about that.

A first step would be to print the exception raised by `Bi_outbuf.add_substring` as well as the state of the output buffer (the `int` fields in https://github.com/mjambon/biniou/blob/master/src/bi_outbuf.mli#L3-L40). The workflow for this is to `git clone` yojson, edit it, and `opam pin` it so as to use this version instead of the one coming from the opam repository. That will take care of rebuilding all the opam packages that depend on it. Then you can rebuild your application and see what's going on.

It may be a simple bug in `Bi_outbuf` that hasn't been discovered so far, although it's a little strange that it only shows up given how heavily it's been used (in terms of amount of input processed).

**Comment by NathanReb** [comment]
Yes I already did that and the bug was indeed coming from somewere else, `to_channel` just received a closed channel.

Reraising the exception made it pretty easy to figure out!

**Comment by mjambon** [comment]
Great to hear. I opened a separate issue to the task of not hiding exceptions (#62) so this won't happen again.
